### ISSUE TITLE
Avoid sudo for running docker

### ISSUE THREAD

**Issue by katilp** [Solenoidata/VM-Azure#1]
If I recall correctly, running `docker` with `sudo` led to some problems further on.

Check if you can avoid it by following these instructions on the VM:
https://docs.docker.com/engine/install/linux-postinstall/

I'm not sure if it matters in this context but it would be good for consistency.

That would be (the first command is here just for the record, it is not needed)

```
azureuser@opendata:~$ sudo groupadd docker
groupadd: group 'docker' already exists
azureuser@opendata:~$ sudo usermod -aG docker $USER
azureuser@opendata:~$ newgrp docker

```

**Comment by dianitamart** [comment]
It works!
